# Generated by Django 4.1.7 on 2023-03-31 19:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Responsibilities',
            fields=[
                ('resp_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('resp_name', models.CharField(max_length=15)),
                ('resp_type', models.CharField(max_length=3)),
                ('resp_action', models.CharField(max_length=3)),
                ('resp_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserResponsibilities',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('resp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responsibilities.responsibilities')),
            ],
        ),
    ]
