# Generated by Django 4.1.7 on 2023-03-21 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('order_id', models.UUIDField(primary_key=True, serialize=False)),
                ('order_desc', models.TextField()),
                ('order_status', models.IntegerField(default=0)),
                ('invoice_number', models.IntegerField()),
                ('invoice_status', models.IntegerField(default=0)),
                ('invoice_atm', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier')),
            ],
        ),
    ]
