# Generated by Django 4.1.7 on 2023-03-21 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='login_email',
            new_name='username',
        ),
    ]
