# Generated by Django 4.1.7 on 2023-03-21 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dispensing', '0001_initial'),
        ('stock', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solddrug',
            name='store_stock_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.storestock'),
        ),
        migrations.AddField(
            model_name='dispensing',
            name='store_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store'),
        ),
        migrations.AddField(
            model_name='dispensing',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
