# Generated by Django 4.1.7 on 2023-03-21 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drug', '0001_initial'),
        ('purchaseorder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseDrug',
            fields=[
                ('purchase_drug_id', models.UUIDField(primary_key=True, serialize=False)),
                ('order_quantity', models.IntegerField()),
                ('invoice_quantity', models.IntegerField()),
                ('drug_cost', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drug_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drug.drug')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchaseorder.purchaseorder')),
            ],
        ),
    ]
